### ISSUE TITLE
regarding the format of microbiome dataset

### ISSUE THREAD

**Issue by Muneer111** [riffomonas/baxter_data#2]
Hi @pschloss 
Hope you are fine and doing good
I am new to R and I watch your videos on you tube to go ahead and start analysis the data.
Now I have a basic question, once I analyze the data using any stand alone or web-based software like QIIME2 , MetaPhlAn or MG-RAST.   I get my data in the form of OTUs/ASVs for each sample. 
Now my question here is to how to arrange this data, may be in excel sheet or any other format.
What to put in columns and what in rows.
Thanks and Regards

**Comment by pschloss** [comment]
Thanks for your question. The data were outputted from mothur as tab-separated values (TSV) files. I'm not familiar with the output from these other software tools so I'm not going to be much help in guiding you. Naturally, I'd encourage you to use mothur instead :)

Pat
